/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Dzw9UBd5ZL0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Calendar } from "@/components/ui/calendar";

export function Dashy() {
  return (
    <div className="w-full h-full">
      <div className="grid gap-6 p-6 sm:p-10">
        <Card>
          <CardHeader>
            <CardTitle>Todays Appointments</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Appointment</TableHead>
                  <TableHead>Start Time</TableHead>
                  <TableHead>End Time</TableHead>
                  <TableHead>Duration</TableHead>
                  <TableHead>Client</TableHead>
                  <TableHead>Contact</TableHead>
                  <TableHead>Notes</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Consultation</TableCell>
                  <TableCell>9:00 AM</TableCell>
                  <TableCell>9:30 AM</TableCell>
                  <TableCell>30 min</TableCell>
                  <TableCell>
                    <div className="font-medium">John Doe</div>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      johndoe@example.com
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      (123) 456-7890
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      Discuss treatment plan
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Haircut</TableCell>
                  <TableCell>10:00 AM</TableCell>
                  <TableCell>11:00 AM</TableCell>
                  <TableCell>60 min</TableCell>
                  <TableCell>
                    <div className="font-medium">Jane Smith</div>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      janesmith@example.com
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      (987) 654-3210
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      Trim and style
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Manicure</TableCell>
                  <TableCell>11:30 AM</TableCell>
                  <TableCell>12:15 PM</TableCell>
                  <TableCell>45 min</TableCell>
                  <TableCell>
                    <div className="font-medium">Bob Johnson</div>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      bobjohnson@example.com
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      (555) 555-5555
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      French manicure
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Massage</TableCell>
                  <TableCell>1:00 PM</TableCell>
                  <TableCell>2:30 PM</TableCell>
                  <TableCell>90 min</TableCell>
                  <TableCell>
                    <div className="font-medium">Sarah Lee</div>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      sarahlee@example.com
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      (111) 222-3333
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="text-gray-500 dark:text-gray-400 text-sm">
                      Deep tissue massage
                    </div>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Calendar View</CardTitle>
          </CardHeader>
          <CardContent>
            <Calendar
              className="w-full [&_td]:w-16 [&_td]:h-16 [&_th]:w-16 [&_[name=day]]:w-16 [&_[name=day]]:h-16 [&>div]:space-x-0 [&>div]:gap-6"
              mode="single"
              numberOfMonths={1}
            />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
